name: Build and Publish

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: Package
          path: path/to/artifacts
      - name: Get current version
        run: |
          echo ${{steps.download.outputs.download-path}}/versions.json
          echo "I should be Github Action!"
      - uses: gradle/gradle-build-action@v2
        run: |
          chmod +x ./gradlew
          ./gradlew setCurrentVersion --projectVersion=0.10.0 --alias=core clean build
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
          retention-days: 1
