name: Build and Publish

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew build
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
          retention-days: 1
