name: Build and Publish

on:
  workflow_call:

jobs:
  getVersions:
    runs-on: ubuntu-latest

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - name: download versions
        id: download
        with:
          name: Package
          path: path/to/artifacts
          run: |
            echo ${{steps.download.outputs.download-path}}/versions.json
            echo "I should be Github Action!"
      - uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew setCurrentVersion --projectVersion=0.10.0 --alias=core clean build
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs
          retention-days: 1
