name: Deploy; Dev environments.

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow
        run: echo "Hello from deployment of dev environments workflow!"
