name: Deploy=Dev environments.

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        id: deploy
        with:
          name: deploy
          path: path/to/artifacts

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifacts

      - name: "Echo download path"
        run: |
          echo "${{ steps.download.outputs.deploy-path }}"
          for FILE in ${{ steps.download.outputs.deploy-path }}/*.jar; do
              echo "$FILE";
          done;

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/download-artifact@v3
#         id: download
#         with:
#           name: Package
#           path: path/to/artifacts

#       - name: Display structure of downloaded files
#         run: ls -R
#         working-directory: path/to/artifacts

#       - name: "Echo download path"
#         run: echo ${{steps.download.outputs.download-path}}

#       - name: print files.
#         run: |
#           regex="[0-9]\.[0-9]\.[0-9]\.jar"
#           for FILE in ${{steps.download.outputs.download-path}}/*.jar; do
#             if [[ $FILE =~ $regex ]];
#             then
#               echo "$FILE";
#               mkdir deploy;
#               cp -r "$FILE" "${GITHUB_WORKSPACE}/deploy/"
#             else
#               echo "No match: $FILE";
#             fi
#           done;
#       - name: Print Deploy Folder
#         run: |
#           for FILE in ${GITHUB_WORKSPACE}/deploy/*.jar; do
#             echo "File $FILE";
#           done;
