name: Deploy; Dev environments.

on:
  workflow_call:

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow
        run: echo "Workflow - Deployment"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build/libs
        uses: actions/download-artifact@v3
        with:
          name: package
        run: |
          for f in build/libs/*.jar; do 
            echo ${f};
          done;
