name: Deploy; Dev environments.

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        id: download
        with:
          name: Package
          path: path/to/artifacts

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifacts

      - name: "Echo download path"
        run: echo ${{steps.download.outputs.download-path}}

      - name: print files.
        run: |
          regex="[0-9]\.[0-9]\.[0-9]\.jar"
          for FILE in ${{steps.download.outputs.download-path}}/*.jar; do
            if [[ "$FILE" =~ "$regex" ]];
            then
              echo "$FILE";
            else
              echo "No match: $FILE";
            fi  
          done;
