name: Test

on:
  workflow_call:
    inputs:
      core-gradle-name:
        required: true
        type: string
      core-directory-name:
        required: true
        type: string
      adp-gradle-name:
        required: true
        type: string
      adp-directory-name:
        required: true
        type: string
      dp-gradle-name:
        required: true
        type: string
      dp-directory-name:
        required: true
        type: string
      oc-gradle-name:
        required: true
        type: string
      oc-directory-name:
        required: true
        type: string
      sim-gradle-name:
        required: true
        type: string
      sim-directory-name:
        required: true
        type: string

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Core
        run: |
          echo "core-gradle=${{ core-gradle-name }}"
          echo "core-directory=${{ core-directory-name }}"

          echo "adp-gradle=${{ adp-gradle-name }}"
          echo "adp-directory=${{ adp-directory-name }}"

          echo "dp-gradle=${{ dp-gradle-name }}"
          echo "dp-directory=${{ dp-directory-name }}"

          echo "oc-gradle=${{ oc-gradle-name }}"
          echo "oc-directory=${{ oc-directory-name }}"

          echo "sim-gradle=${{ sim-gradle-name }}"
          echo "sim-directory=${{ sim-directory-name }}"
