name: Test

on:
  workflow_call:
    inputs:
      core-gradle-name:
        required: true
        type: string
      core-directory-name:
        required: true
        type: string
      adp-gradle-name:
        required: true
        type: string
      adp-directory-name:
        required: true
        type: string
      dp-gradle-name:
        required: true
        type: string
      dp-directory-name:
        required: true
        type: string
      oc-gradle-name:
        required: true
        type: string
      oc-directory-name:
        required: true
        type: string
      sim-gradle-name:
        required: true
        type: string
      sim-directory-name:
        required: true
        type: string

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Core
        run: |
          echo "core-gradle=${{ inputs.core-gradle-name }}"
          echo "core-directory=${{ inputs.core-directory-name }}"
          echo "adp-gradle=${{ inputs.adp-gradle-name }}"
          echo "adp-directory=${{ inputs.adp-directory-name }}"
          echo "dp-gradle=${{ inputs.dp-gradle-name }}"
          echo "dp-directory=${{ inputs.dp-directory-name }}"
          echo "oc-gradle=${{ inputs.oc-gradle-name }}"
          echo "oc-directory=${{ inputs.oc-directory-name }}"
          echo "sim-gradle=${{ inputs.sim-gradle-name }}"
          echo "sim-directory=${{ inputs.sim-directory-name }}"
